spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

redis:
  host: localhost
  port: 6379
  password: test
  time-to-live:
    verification-code: 600
  key-prefix:
    verification-code: 'antevorta:verification-code:'
    onlinestores:
      ebay: 'antevorta:access-key:ebay:'

mailgun:
  base-url: 'https://api.mailgun.net/'
  domain: ''
  private-api-key: ''

#Encryptor (preferably both 16 characters long)
encryption:
  secretKey: someSecretKey
  initializationVector: someInitializationVector

server:
  port: 8081

logging:
  level:
    com:
      antevorta: DEBUG